import Link from "next/link";
import { Navbar } from "../../components/Navbar";

export const legalPage = () => {
  return (
    <div
      className={`prose mx-auto prose-invert py-16 prose-headings:text-indigo-400 prose-h1:text-purple-500 text-indigo-100 font-wsans prose-headings:font-poppins h-screen overflow-auto lg:w-[90vw]`}
    >
      <Navbar />
      <h1>Privacy Policy for Dazai</h1>
      <p>
        Dazai is a Discord bot that allows users to customize their own
        backgrounds and provides generative features. This privacy policy
        explains what data Dazai collects, how it is used, and how it is stored.
      </p>

      <h2>Data Collection</h2>
      <p>
        Dazai collects user-submitted data, such as images and commands
        submitted via our website or Discord. This data is used to provide
        generative features and for debugging and analytics purposes.
      </p>

      <h2>Purpose of Data Collection</h2>
      <p>
        The data collected by Dazai is used to create generative features, such
        as allowing users to customize their own backgrounds. This data is also
        used for debugging and analytics purposes, which helps us improve
        Dazai's functionality and performance.
      </p>

      <h2>Data Access</h2>
      <p>
        Only the bot owner has access to the data collected by Dazai. No third
        parties have access to this data unless required, for example, when the
        bot generates a rank card with a user-provided background that exceeds
        the file limit and needs to be uploaded to a file hosting service.
      </p>

      <h2>Data Storage</h2>
      <p>
        The data collected by Dazai is stored on a MongoDB instance separate
        from the bot server. We take measures to ensure the security of this
        data, including password protection.
      </p>

      <h2>Data Deletion</h2>
      <p>
        Users can request that their data be deleted by contacting the bot owner
        via DM on Discord (
        <a href="https://discord.com/users/295391243318591490">Tet#6000</a>) or{" "}
        <a href="mailto:tet@tet.moe">email</a>. If the bot is shut down or no
        longer in use, user data will remain until it is deleted during a
        cleanup process.
      </p>

      <h2>Additional Information</h2>
      <p>
        Users should be aware that their data is used for generative features,
        debugging, and analytics purposes. If any changes are made to Dazai's
        data practices, this privacy policy will be updated accordingly.
      </p>
      <h1>Terms of Service Agreement for Dazai</h1>
      <ol>
        <li>
          <h2>Use of Dazai Discord Bot</h2>
          <p>
            By using Dazai Discord Bot, you agree to abide by these Terms of
            Service. Dazai Discord Bot is intended for legal and non-hateful
            use. Any violation of this agreement or any misuse of the bot may
            result in the user being banned or blocked at the discretion of the
            bot owner.
          </p>
        </li>
        <li>
          <h2>Content Allowed</h2>
          <p>
            Dazai Discord Bot allows users to upload or generate any legal
            content. Any illegal content is strictly prohibited and may result
            in the user being banned or blocked.
          </p>
        </li>
        <li>
          <h2>User-Generated Content</h2>
          <p>
            Users own the rights to their own content generated by Dazai Discord
            Bot. However, bot-generated content must be accredited unless deemed
            otherwise.
          </p>
        </li>
        <li>
          <h2>Privacy and Data Protection</h2>
          <p>
            Dazai Discord Bot handles user privacy and data protection in
            accordance with its{" "}
            <Link href="/legal/privacy">Privacy Policy</Link>. Please review the
            Privacy Policy carefully to understand how Dazai Discord Bot
            collects, uses, and stores your data.
          </p>
        </li>
        <li>
          <h2>Liability</h2>
          <p>
            The user is solely liable for any damages or harm caused by using
            Dazai Discord Bot. Dazai Discord Bot is not responsible for any
            loss, injury, or damage resulting from the use or inability to use
            the bot.
          </p>
        </li>
        <li>
          <h2>Dispute Resolution</h2>
          <p>
            If there are any issues or complaints about Dazai Discord Bot or its
            services, please contact the bot owner via DM on Discord (
            <a href="https://discord.com/users/295391243318591490">Tet#6000</a>)
            or email (<a href="mailto:tet@tet.moe">tet@tet.moe</a>).
          </p>
        </li>
      </ol>
    </div>
  );
};
export default legalPage;
