import Link from "next/link";
import { Navbar } from "../../components/Navbar";

export const tosPage = () => {
  return (
    <div
      className={`prose mx-auto prose-invert py-16 prose-headings:text-indigo-500 font-wsans prose-headings:font-poppins`}
    >
        <Navbar />
      <h1>Terms of Service Agreement for Dazai</h1>
      <ol>
        <li>
          <h2>Use of Dazai Discord Bot</h2>
          <p>
            By using Dazai Discord Bot, you agree to abide by these Terms of
            Service. Dazai Discord Bot is intended for legal and non-hateful
            use. Any violation of this agreement or any misuse of the bot may
            result in the user being banned or blocked at the discretion of the
            bot owner.
          </p>
        </li>
        <li>
          <h2>Content Allowed</h2>
          <p>
            Dazai Discord Bot allows users to upload or generate any legal
            content. Any illegal content is strictly prohibited and may result
            in the user being banned or blocked.
          </p>
        </li>
        <li>
          <h2>User-Generated Content</h2>
          <p>
            Users own the rights to their own content generated by Dazai Discord
            Bot. However, bot-generated content must be accredited unless deemed
            otherwise.
          </p>
        </li>
        <li>
          <h2>Privacy and Data Protection</h2>
          <p>
            Dazai Discord Bot handles user privacy and data protection in
            accordance with its <Link href="/legal/privacy">Privacy Policy</Link>.
            Please review the Privacy Policy carefully to understand how Dazai
            Discord Bot collects, uses, and stores your data.
          </p>
        </li>
        <li>
          <h2>Liability</h2>
          <p>
            The user is solely liable for any damages or harm caused by using
            Dazai Discord Bot. Dazai Discord Bot is not responsible for any
            loss, injury, or damage resulting from the use or inability to use
            the bot.
          </p>
        </li>
        <li>
          <h2>Dispute Resolution</h2>
          <p>
            If there are any issues or complaints about Dazai Discord Bot or its
            services, please contact the bot owner via DM on Discord (
            <a href="https://discord.com/users/295391243318591490">Tet#6000</a>) or
            email (<a href="mailto:tet@tet.moe">tet@tet.moe</a>).
          </p>
        </li>
      </ol>
    </div>
  );
};
export default tosPage;
